// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI0o3zo_NlWc8fKgVv6VHfCDmV9K-wBfg',
    appId: '1:1037773373862:web:217ec25e11c82d5e6dcf67',
    messagingSenderId: '1037773373862',
    projectId: 'movetime-96b22',
    authDomain: 'movetime-96b22.firebaseapp.com',
    storageBucket: 'movetime-96b22.firebasestorage.app',
    measurementId: 'G-GHV5172P3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ89aSXyKsOhg8kJn0tA5H5gyIs0tCKbM',
    appId: '1:1037773373862:android:4234115260ae99816dcf67',
    messagingSenderId: '1037773373862',
    projectId: 'movetime-96b22',
    storageBucket: 'movetime-96b22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsZnBk65x4_JwAHMq3dH9VMeANul9dL9c',
    appId: '1:1037773373862:ios:305003a3b761e0536dcf67',
    messagingSenderId: '1037773373862',
    projectId: 'movetime-96b22',
    storageBucket: 'movetime-96b22.firebasestorage.app',
    iosBundleId: 'com.example.daLtuddd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsZnBk65x4_JwAHMq3dH9VMeANul9dL9c',
    appId: '1:1037773373862:ios:305003a3b761e0536dcf67',
    messagingSenderId: '1037773373862',
    projectId: 'movetime-96b22',
    storageBucket: 'movetime-96b22.firebasestorage.app',
    iosBundleId: 'com.example.daLtuddd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI0o3zo_NlWc8fKgVv6VHfCDmV9K-wBfg',
    appId: '1:1037773373862:web:1e5ab56729958fe16dcf67',
    messagingSenderId: '1037773373862',
    projectId: 'movetime-96b22',
    authDomain: 'movetime-96b22.firebaseapp.com',
    storageBucket: 'movetime-96b22.firebasestorage.app',
    measurementId: 'G-1HV2VFC5LS',
  );
}
